import { Client } from 'pg';
import { existsSync } from 'node:fs';
import { readFile, writeFile } from 'node:fs/promises';
import { WATCHLIST_FILE } from './lib/paths.js';

const DRY_RUN = process.env.DRY_RUN === '1';

interface DbRow {
  csfd_id: number;
  source: 'films' | 'series' | 'tv_shows';
}

interface WatchlistFile {
  description?: string;
  generatedAt?: string;
  source?: string;
  ids: number[];
}

async function fetchIdsFromDb(): Promise<DbRow[]> {
  const connectionString = process.env.DB_RO_URL;
  if (!connectionString) {
    throw new Error('DB_RO_URL env var is required');
  }

  const client = new Client({ connectionString });
  await client.connect();

  try {
    const sql = `
      SELECT csfd_id, 'films'    AS source FROM films    WHERE csfd_id IS NOT NULL
      UNION
      SELECT csfd_id, 'series'   AS source FROM series   WHERE csfd_id IS NOT NULL
      UNION
      SELECT csfd_id, 'tv_shows' AS source FROM tv_shows WHERE csfd_id IS NOT NULL
      ORDER BY csfd_id ASC
    `;
    const res = await client.query<DbRow>(sql);
    return res.rows;
  } finally {
    await client.end();
  }
}

async function loadExistingWatchlist(): Promise<WatchlistFile> {
  if (!existsSync(WATCHLIST_FILE)) {
    return { ids: [] };
  }
  try {
    return JSON.parse(await readFile(WATCHLIST_FILE, 'utf8')) as WatchlistFile;
  } catch {
    return { ids: [] };
  }
}

function diff(previous: number[], current: number[]): { added: number[]; removed: number[] } {
  const prev = new Set(previous);
  const curr = new Set(current);
  return {
    added: [...curr].filter((id) => !prev.has(id)).sort((a, b) => a - b),
    removed: [...prev].filter((id) => !curr.has(id)).sort((a, b) => a - b)
  };
}

async function main(): Promise<void> {
  console.log(`csfd-data-hub sync-watchlist${DRY_RUN ? ' (DRY RUN)' : ''}`);

  const rows = await fetchIdsFromDb();
  console.log(`Fetched ${rows.length} rows from cr prod DB.`);

  const byId = new Map<number, Set<DbRow['source']>>();
  for (const row of rows) {
    const set = byId.get(row.csfd_id) ?? new Set();
    set.add(row.source);
    byId.set(row.csfd_id, set);
  }

  const ids = [...byId.keys()].sort((a, b) => a - b);
  const previous = await loadExistingWatchlist();
  const { added, removed } = diff(previous.ids, ids);

  console.log(`Unique IDs: ${ids.length} (+${added.length}, -${removed.length} vs. previous)`);
  if (added.length > 0 && added.length <= 20) {
    console.log('  added:', added.join(', '));
  }
  if (removed.length > 0 && removed.length <= 20) {
    console.log('  removed:', removed.join(', '));
  }

  const out: WatchlistFile = {
    description:
      'Auto-generated by scripts/sync-watchlist.ts from cr production DB (films, series, tv_shows). Do not edit by hand.',
    generatedAt: new Date().toISOString(),
    source: 'cr.films + cr.series + cr.tv_shows (csfd_id IS NOT NULL)',
    ids
  };

  if (!DRY_RUN) {
    await writeFile(WATCHLIST_FILE, JSON.stringify(out, null, 2) + '\n', 'utf8');
    console.log(`Wrote ${WATCHLIST_FILE}`);
  } else {
    console.log('(dry run — no file written)');
  }
}

main().catch((err) => {
  console.error('Fatal:', err);
  process.exit(1);
});
